### ISSUE TITLE
how can i get ematates

### ISSUE THREAD

**Issue by hessamza** [picqer/moneybird-php-client#100]
I use this code:
        $moneyBird = new Moneybird($this->connect());
       $estimate = $moneyBird->estimate()->get();
this return :Exceptions\ApiException: Error 401: {"error":"No access to estimates"}

**Comment by casperbakker** [comment]
It looks like your account or user has not access in Moneybird itself to the Estimates feature. The API reflects that access.

You should look in your Moneybird account and see if this user has the right permissions. Otherwise you could ask the Moneybird helpdesk.
