### ISSUE TITLE
Add support for sales invoice attachments

### ISSUE THREAD

**Issue by dannyvw** [picqer/moneybird-php-client#102]
https://developer.moneybird.com/api/sales_invoices/#post_sales_invoices_id_attachments

See this commit for a possible solution
https://github.com/dannyvw/moneybird-php-client/commit/72ece2218fc284056e7f54e89464b65e69a14273

**Comment by dannyvw** [comment]
@stephangroen This issue is not solved?

**Comment by stephangroen** [comment]
No, if it's needed a PR is welcome.
