### ISSUE TITLE
Tag 0.2.1 missing on repo

### ISSUE THREAD

**Issue by peterjaap** [picqer/moneybird-php-client#11]
I think you forgot to add a new tag on the repo, since these two files differ;

https://github.com/picqer/moneybird-php-client/blob/master/src/Picqer/Financials/Moneybird/Entities/SalesInvoiceDetail.php

https://github.com/picqer/moneybird-php-client/blob/v0.2.0/src/Picqer/Financials/Moneybird/Entities/SalesInvoiceDetail.php

(the 'period' attribute is present in master, but not in v0.2.0)

**Comment by stephangroen** [comment]
Hadn't released yet, because this change was soon after another one. Expected some more changes, so was waiting to do a release with all changes at once. Since other changes won't be added within the next few days, I've tagged v0.2.1.
