### ISSUE TITLE
FindOne::find() should distinguish between "unknown id" and "failed request".

### ISSUE THREAD

**Issue by donquixote** [picqer/moneybird-php-client#110]
The `Picqer\Financials\Moneybird\Actions\FindOne::find()` is used to find e.g. a contact for a given id.
It does a request to moneybird, which has 3 possibly outcomes:
1. The entity (e.g. contact) exists, and the record is returned.
2. The entity (e.g. contact) does not exist, and a 404 with a json like `{"error":"record not found","symbolic":{"customer_id":"not_found"}}` is returned.
3. The connection or the request fails, for whichever reason. This can also result in 404.

Currently, `Picqer\Financials\Moneybird\Actions\FindOne::find()` does not properly distinguish between cases 2 and 3.

In both cases:
- Guzzle throws an exception, e.g. `GuzzleHttp\Exception\ClientException`, because the client is configured with `'http_errors' => true`. This still contains the complete response.
- `Picqer\Financials\Moneybird\Connection::parseExceptionForErrorMessages()` converts this into an `Picqer\Financials\Moneybird\Exceptions\ApiException`. This exception class is much less convenient, and also does not contain the parent exception.
- `Picqer\Financials\Moneybird\Actions\FindOne::find()` does not care to catch any exceptions.

This means a caller needs to parse the exception message to find out which of the cases 2. or 3. is happening.

E.g. I am having a case where I have a record in the local database referencing moneybird contact ids.
If the contact no longer exists in moneybird, I should delete the local record.
However, if the connection failed, it means that the contact might still exist in moneybird, and deleting the local record would be a grave mistake.

## Proposed change

I see the following options.
1. Let `Picqer\Financials\Moneybird\Actions\FindOne::find()` return NULL if the entity does not exist, and throw an exception if there are connection problems. This is a BC break.
2. Create a second method e.g. `Picqer\Financials\Moneybird\Actions\FindOne::findOrNull()` with the described behavior, and leave the other method as it is. This is no BC break, but clutters the API.
3. Throw a different exception type in FindOne::find(), if the entity does not exist.
4. Throw a different exception type in Connection::get() for 404, with a dedicated property and getter for the json data.
5. Change the `'http_errors' => true` parameter for the Guzzle client.

**Comment by stephangroen** [comment]
Option 1 seems to most logical in my opinion, but because it's a breaking change I think we should try and see if we can work around this. Need to remember this as a possible change for a new major release.

I am leaning towards option 2 for now. It does clutter the API a bit, but has the least impact and keeps it readable. It would also be most close to the proposed functionality in option 1, which we might add in the new major version.
