### ISSUE TITLE
Downloadable package without composer

### ISSUE THREAD

**Issue by Beee4life** [picqer/moneybird-php-client#112]
I want to use this in a Wordpress plugin on a server without Composer.
So I placed into my plugin subfolder /vendor and I added [this package](https://github.com/paynl/sdk#installation-without-composer) (for the autoload file).

I removed only the paynl folder and changed the autoload.php location in my plugin.
It seems to work only partially, but I was wondering if it is possible (maybe with some tweaks) to do it like this.

Follow-up question: will you make a downloadable package without composer ?

**Comment by stephangroen** [comment]
There is a lot of info on this on the internet. The way to use Composer packages without Composer is the same for most of the available packages. See for example: https://stackoverflow.com/questions/40545795/how-do-i-install-composer-php-packages-without-composer

**Comment by Beee4life** [comment]
I'm sorry, but I have searched and tried various options but I couldn't make it work yet, that's why I asked your for help.

I really hope you can help me here, because I'm very stuck....

**Comment by stephangroen** [comment]
https://php-download.com/package/picqer/moneybird-php-client

Download the files, extract them to your project. Use the autoloader as specified in the index.php file. Then you can use this library as specified in README.

**Comment by Beee4life** [comment]
That was what I was looking for. Thank you, appreciate it.

I put it in my plugin and the first try was a success.
Gonna check out the rest tomorrow.
