### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by brammetjeh** [picqer/moneybird-php-client#113]
When i do 
 $contacts = $moneybird->contact()->get('all');

I get the first 50 contacts how can i get them all or pagination?

Tnx for the anser in advance

**Comment by davidspeijer** [comment]
Did you find an answer? I also need this :)

**Comment by davidspeijer** [comment]
Found:
$salesInvoices = $moneybird->salesInvoice()->filterAll(['period' => '20171201..20171231']);

So I assume that     $taxRates = $moneybird->taxRate()->getAll(); is also working :)
