### ISSUE TITLE
No stable composer versions installable, according to composer.

### ISSUE THREAD

**Issue by EraYaN** [picqer/moneybird-php-client#12]
Could you update your composer package to have versions and a stable and dev line? (Might be based on git branches) 

Especially a stable version.

**Comment by stephangroen** [comment]
What does your composer.json look like? The package has tagged releases, so it should be considered stable. You should require a release though, something like:

``` json
    "require": {
        "picqer/moneybird-php-client": "^0.2.1"
    }
```

**Comment by EraYaN** [comment]
After I manually added it to my composer.json it did download, I have no idea why it complained at first.

I'll close this issue.
