### ISSUE TITLE
Prevent "Missing return statement" in Connection methods.

### ISSUE THREAD

**Issue by donquixote** [picqer/moneybird-php-client#122]
Some methods in class Connection call `->parseExceptionForErrorMessages()`, which always throws an exception.

The IDE does not understand this, and complains about "Missing return statement".

Proposed solution:
Instead of throwing an exception, let `function parseExceptionForErrorMessages()` _return_ the exception object.
Then throw the returned exception object when calling the method.

**Comment by donquixote** [comment]
Also, wrap previous exception into new exception as 3rd parameter.

**Comment by donquixote** [comment]
Pull request: #133 
Other commits outside this pull requests please ignore..

**Comment by donquixote** [comment]
Note that the checkWhetherRateLimitHasBeenReached() can still throw exceptions. So the method itself now can either throw or return an exception.

I am not sure if I like this change. It does get rid of the IDE warning for missing return point.
Unfortunately there is no way to formalize that a method "always throws".

**Comment by stephangroen** [comment]
It's a bit odd at first, but I think I like it. It does provide a little more consistency too.
