### ISSUE TITLE
Add @property docs on entities

### ISSUE THREAD

**Issue by donquixote** [picqer/moneybird-php-client#125]
I am splitting this out of #124, because it is big enough on its own and maybe needs more discussion.

**Comment by donquixote** [comment]
One open question is the types of each property. Should we always make it `mixed`, or should we make an effort to determine the correct type for each property?

**Comment by stephangroen** [comment]
If you can determine the type it's better, but having a @property is still better than nothing for easier coding. I'll leave it up to you.
