### ISSUE TITLE
listVersions for estimates only returning id?

### ISSUE THREAD

**Issue by vissr** [picqer/moneybird-php-client#141]
Has anyone experienced any trouble with the synchronization api for the estimates model?
Suddenly running the following code:

`$estimateVersions = $moneybird->estimate()->listVersions();`

Results in the following:

![schermafbeelding 2018-03-02 om 16 24 15](https://user-images.githubusercontent.com/6206289/36906432-315c8194-1e36-11e8-9350-4df2aec69966.png)

In short, the only thing returned is the id, but no version.
Anyone else experienced trouble with this?

**Comment by stephangroen** [comment]
It happens because the Estimates entity does not have a version attribute. You can add it to the fillables at https://github.com/picqer/moneybird-php-client/blob/master/src/Picqer/Financials/Moneybird/Entities/Estimate.php#L29 and then it will work. Please submit a PR :)
