### ISSUE TITLE
After one request, need to refresh AuthorizationCode

### ISSUE THREAD

**Issue by LegacyProgrammer** [picqer/moneybird-php-client#142]
After I have succesfully connected once, I need to login again to get the refreshed AuthorizationCode.

Anyone had this issue before?

**Comment by stephangroen** [comment]
No, are you sure you are sending the correct codes?

**Comment by LegacyProgrammer** [comment]
It is working now, because I commented out the setAuthorizationCode(). Now i statically added the accessToken.

When trying to repeat this process, i am unable to receive the AccessToken with getAccessToken().

**Comment by stephangroen** [comment]
Does the example work for you?
