### ISSUE TITLE
Increase robustness by using ::class constant

### ISSUE THREAD

**Issue by holtkamp** [picqer/moneybird-php-client#152]
Currently the aimed PHP version is `5.5.0`. [As of PHP `5.5.0` the `::class` constant is available](http://php.net/manual/en/language.oop5.constants.php). This can be useful to increase robustness. For example: currently the `Model::$multipleNestedEntities` array uses plain strings to refer to an Entity:

```php
protected $multipleNestedEntities = [
        'custom_fields' => [
            'entity' => 'ContactCustomField',
            'type' => self::NESTING_TYPE_NESTED_OBJECTS,
        ],
    ];
```

this approach is more robust and makes it easier for IDEs to understand what is going on / refactor, etc:

```php
protected $multipleNestedEntities = [
        'custom_fields' => [
            'entity' => ContactCustomField::class,
            'type' => self::NESTING_TYPE_NESTED_OBJECTS,
        ],
    ];
```

Since the Fully Qualified Classname (FQCN) will be used, this has some impact, for example in https://github.com/picqer/moneybird-php-client/blob/6e8df3699948d6d4d4ca76e3cee5adec3d722965/src/Picqer/Financials/Moneybird/Model.php#L278-L301 the namespace does not have to be prefixed anymore.

**Comment by stephangroen** [comment]
Yes, this is indeed a lot better. Changes are welcome :)

**Comment by holtkamp** [comment]
Merged in https://github.com/picqer/moneybird-php-client/pull/155
