### ISSUE TITLE
Deleting contactswon't work

### ISSUE THREAD

**Issue by jochem4207** [picqer/moneybird-php-client#16]
Fatal error: Uncaught exception 'Picqer\Financials\Moneybird\Exceptions\ApiException' with message 'Error 404: {"error":"404 Not Found"}

I get the fatal error when trying to delete: 
 // Create the Moneybird client
        $connection = $this->connect($this->redirectUrl, $this->clientId, $this->clientSecret);
        $connection->setAdministrationId($this->administrationId);
        $moneybird = new \Picqer\Financials\Moneybird\Moneybird($connection);

```
    $moneybird->contact()->delete();
```

I've used the example and added that line after making connection

Other functions work fine, awesome client :+1:

**Comment by stephangroen** [comment]
Thanks :)

You cannot create a delete request for all contacts. You'll have to get a contact first and then delete it. For example:

``` php
$contact = $moneybird->contact()->find(89672345789233);
$contact->delete();
```

or this to use only 1 request:

``` php
$moneybird->contact(['id' => 89672345789233])->delete();
```
