### ISSUE TITLE
Contact custom_fields_attributes not saving

### ISSUE THREAD

**Issue by pinside** [picqer/moneybird-php-client#162]
I'm trying to save some custom fields along with my new contact. The contact is saving just fine, but the custom fields do not. 

Am I doing something wrong here?

```
$contact = $moneybird->contact();
$contact->company_name = 'My Company';
$contact->firstname = 'Robin';
$contact->lastname = 'Johnson';
$contact->city = 'Amsterdam';
$contact->country = 'NL';
$contact->customer_id = 'user_1001';
$contact->send_invoices_to_email = "some@email.com";

$customFields = [];

$customField1 = $moneybird->contactCustomField();
$customField1->id = 231535530648536173;
$customField1->value = 'robin';
$customFields[] = $customField1;

$customField2 = $moneybird->contactCustomField();
$customField2->id = 231535726377829842;
$customField2->value = '1001';
$customFields[] = $customField2;

$contact->custom_fields_attributes = $customFields;

$contact->save();
```

I got the ID values from the browser URL bar when editing my custom field in MoneyBird. Not sure if that's correct but all examples are showing long integers for id's.

Thanks!

**Comment by basvandertogt** [comment]
I ran into the same issue. Somebody know a solution?

**Comment by timinho** [comment]
I'm experiencing exactly the same.

**Comment by tss68nl** [comment]
Assign the array to $contact->custom_fields instead of $contact->custom_fields_attributes

**Comment by timinho** [comment]
When I do this @tss68nl :

$customFields = [];

$customFieldAttribute = $this->moneyBirdClient->contactCustomField();
$customFieldAttribute->id = '240060053756839136';
$customFieldAttribute->value = 'ABC';
$customFields[] = $customFieldAttribute;

$moneybirdCustomer->custom_fields = $customFields;

I'm getting:
`Cannot use object of type stdClass as array at vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Model.php:236)`

**Comment by tss68nl** [comment]
What I do is constructing the array of objects myself for the custom_fields. I think the parser (_set?) function is pretty picky:

$cf[0] = $moneybird->contactCustomField();
$cf[0]->id = "242123409494980319"; 
$cf[0]->value = 'TEST';
$contact->custom_fields = $cf;

That seems to work for me. Granted the other option should work, but I got the same error you have using the normal way of adding to an empty array.

**Comment by timinho** [comment]
That made my day @tss68nl , thanks a lot!

**Comment by Fleuv** [comment]
The problem is within Model.php ([highlighted here](https://github.com/picqer/moneybird-php-client/blob/e9ce3f6bac47362d98b1a2ffd6be338e512e174d/src/Picqer/Financials/Moneybird/Model.php#L238:L240)):

```
if ($multipleNestedEntities[$attributeName]['type'] === self::NESTING_TYPE_NESTED_OBJECTS) {
    $result[$attributeNameToUse] = (object)$result[$attributeNameToUse];
}
```

This code should be moved one line down, thus after the foreach.

Recommending this patch: [7d332c5@162.patch.txt](https://github.com/picqer/moneybird-php-client/files/3052253/7d332c5%40162.patch.txt)
