### ISSUE TITLE
Not possible to whitelist webhook events

### ISSUE THREAD

**Issue by boedy** [picqer/moneybird-php-client#163]
https://developer.moneybird.com/api/webhooks/#post_webhooks

Events parameter is ignored.

**Comment by ju5t** [comment]
I tried adding it to the fillable but for some reason I can't convert it into an array that is accepted by Moneybird. It would be great if someone can lend a hand here, I'm kind of lost.

**Comment by ju5t** [comment]
https://github.com/picqer/moneybird-php-client/commit/9f2e96bf307adbdd1d6e3a41552cc7fc834244fa added `JSON_FORCE_OBJECT`.

This forces arrays to convert into `"events":{"0":"contact"}`. Unfortunately this is not true for the event keyword in webhooks. It needs to be an array, e.g. `"events":["contact"]`. Removing `JSON_FORCE_OBJECT` from the Model and adding `events` to the fillable of a Webhook works, but potentially breaks other calls.

We could add:

```
    public function json()
    {
        return json_encode($this->attributes);
    }

    public function jsonWithNamespace()
    {
        return $this->json();
    }
```

to the Webhook, which solves the issue without it affecting other calls. We can't access `getArrayWithNestedObjects` as the Model does as it's private, I am not sure if it is required.

Either way some feedback would be appreciated.

**Comment by janmartenjongerius** [comment]
I'm running into the same issue and can confirm that specifically removing the `JSON_FORCE_OBJECT` for webhook calls, combined with adding `events` to the list of fillables, does fix the problem and keeps the client functioning as intended. @ju5t has found a valid approach to the solution, IMHO.
