### ISSUE TITLE
Unable to get the full invoice data

### ISSUE THREAD

**Issue by tss68nl** [picqer/moneybird-php-client#168]
I try to fetch the list of invoices, including all detail data as I have a custom field that is filled with the original invoiceID from the source application. 

However $salesInvoices = $moneybird->salesInvoice()->get(); gives me only a list of the invoices this year. This will be a problem around the new year.

Also $salesInvoices = $moneybird->salesInvoice()->getAll(); gives me exactly the same list on only the invoices this year.

Alternatively I used $moneybird->salesInvoice()->listVersions(); which gives me the full list of objects, but only with the ID filled. For synchronisation I suppose, but seeing my identifier is in the custom_fields normally, I have to request a ->find() for every invoice, which runs over the 150 calls / 5 min cap very very fast.

So.... how will I be able to get the full sales invoice list? 
Is there a way to get them in batches with ->Get(2017) and ->Get(2018) or something?
Can I add a specific custom_field in the listVersions() call?

**Comment by hiranthi** [comment]
SalesInvoices are filterable: [https://developer.moneybird.com/api/sales_invoices/#get_sales_invoices](https://developer.moneybird.com/api/sales_invoices/#get_sales_invoices)

The default is set to 'this_year' (as can be seen in the Moneybird docs). You can change that to prev_year or any of the other possibilities mentioned in the docs. 

```
$moneybird->salesInvoice()->filter([
	'period'			=> 'prev_year'
]);
```

**Comment by tss68nl** [comment]
Perfect, will try that after we deported the family out of the door :)

But I am not sure I've seen the ->filter() option built into the Picqer client? Does this mean that the $moneybird object is a full representation of the full moneybird API?

**Comment by hiranthi** [comment]
If the entity is filterable, you'll see this line on top of the file (like in Estimates.php / SalesInvoice.php / PurchaseInvoice.php):

`use Picqer\Financials\Moneybird\Actions\Filterable;`

`Filterable` would be mentioned inside the class through `use` too btw :)

The contents of how to use Filterable is inside `/Actions/Filterable.php`. The filters that can be used are mentioned in the Moneybird Dev docs.

I haven't come across any limitations in this wrapper (not the current version anyway, have added a few things in the past, but have been using a non-edited version for a while now), but I must say I'm not using everything that can be used. So perhaps there are some that I'm not aware of. 
I always use the Moneybird Dev docs next to the contents of this API wrapper :)

**Comment by tss68nl** [comment]
Closing this: hiranthi's answer is perfect: there are a lot of filter options available. The only thing you must look out for, is that the returned set will become too big in which case it will be truncated. I believe it's 200 items, so whenever you get 200 results per query, you should split to smaller periods.
