### ISSUE TITLE
Workflow Estimates - contact

### ISSUE THREAD

**Issue by striderxfossility** [picqer/moneybird-php-client#18]
I see that i have to give the workflow id when i make an estimates, is it possible that you can include the contact? That when I make a new contact that i can deccide wich workflow to use?

**Comment by stephangroen** [comment]
As stated in the Moneybird docs: Default workflow is used when value is not provided. Should be a valid workflow id.

**Comment by striderxfossility** [comment]
Yes but in contact.php there is no workflow_id.

Im fine with when i create a workflow id at estimate, so you can close this if you like

protected $fillable = [
        'id',
        'company_name',
        'firstname',
        'lastname',
        'attention',
        'address1',
        'address2',
        'zipcode',
        'city',
        'country',
        'email',
        'phone',
        'delivery_method',
        'customer_id',
        'tax_number',
        'chamber_of_commerce',
        'bank_account',
        'send_invoices_to_attention',
        'send_invoices_to_email',
        'send_estimates_to_attention',
        'send_estimates_to_email',
        'sepa_active',
        'sepa_iban',
        'sepa_iban_account_name',
        'sepa_bic',
        'sepa_mandate_id',
        'sepa_mandate_date',
        'sepa_sequence_type',
        'credit_card_number',
        'credit_card_reference',
        'credit_card_type',
        'tax_number_validated_at',
        'created_at',
        'updated_at',
        'notes',
        'custom_fields',
        'version'
    ];
