### ISSUE TITLE
support for retrieving a contact by customer ID

### ISSUE THREAD

**Issue by synio-wesley** [picqer/moneybird-php-client#23]
Could you add support for retrieving a contact by customer ID?

This or similar should be added in Entities/Contact.php:

```
public function findByCustomerId($customerId) {
    $result = $this->connection()->get($this->getUrl() . '/customer_id/' . urlencode($customerId));

    return $this->makeFromResponse($result);
}
```

Thanks!

(Sorry, no time for pull request, but I hope you can implement it, as it is a quick fix)

**Comment by Mailcamp** [comment]
This one was missing! Thanks!

**Comment by stephangroen** [comment]
I'll implement it as soon as I can find some time. Thanks!

**Comment by stephangroen** [comment]
Fixed, will be available in next release (hopefully later this day or start of next week)
