### ISSUE TITLE
Link to Online Invoice

### ISSUE THREAD

**Issue by Silassiai** [picqer/moneybird-php-client#29]
Is there a way to get the link of the online invoice?
Or maybe the mollie ideal link?

**Comment by casperbakker** [comment]
There is a 'url' parameter in the SalesInvoice object. That seems to be the link of the online invoice.

There is no information in the Moneybird documentation about the Mollie iDeal link. Maybe you could ask their support if that is possible to get that from the API.

**Comment by Silassiai** [comment]
this is what i get:
["url"]=>
    string(14) "sales_invoices"

**Comment by stephangroen** [comment]
Hmm I see that's a bug. The entity has a protected $url to hold the location of the endpoint and has a url attribute to hold the public invoice url.

For a quick solution you could do `$salesInvoice->json();` which will use the attributes of the object to create the JSON and retrieve the URL from JSON or do $salesInvoice->attributes() which will return an array of all the attributes, which should hold the key `url` with the public link as the value.

**Comment by Silassiai** [comment]
Works now!!
Thanks for the quick solution/response!!
