### ISSUE TITLE
URL attribute for SalesInvoice gets overwritten

### ISSUE THREAD

**Issue by stephangroen** [picqer/moneybird-php-client#30]
SalesInvoice entity has a protected $url attribute to hold the endpoint location, but also get's a url for the public location of the invoice. The latter is never reachable by just requesting `$salesInvoice->url` and is now only available via `$salesInvoice->attributes()`.

**Comment by roelvanduijnhoven** [comment]
Having troubles with this as well when listing all webhooks.

Quick fix would be to rename `url` to `endpoint` IMO.
