### ISSUE TITLE
Synchronizable and filter

### ISSUE THREAD

**Issue by it-can** [picqer/moneybird-php-client#46]
Hey,

I want to do something like this, but it is not possible? Want to fetch a total number on estimates that are open / late

```
$offers = $moneybird
                ->estimate()
                ->listVersions()
                ->filter([
                    'period' => 'this_year',
                    'state'  => 'open|late',
                ]);
```

without `listVersions()` it works...

**Comment by stephangroen** [comment]
That's not supported at the moment :) `listVersions` is not a chainable method. Both `filter` and `listVersions`  execute an API call to Moneybird. To support this we would need to make these functions configure the request and have an extra function to actually execute the request.

A more easy fix for now would be to add a function to the Synchronizable trait to allow for filtered versions listing.

**Comment by it-can** [comment]
@stephangroen I created a PR, https://github.com/picqer/moneybird-php-client/pull/47
