### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by CNVeerman** [picqer/moneybird-php-client#48]
Hello Stephan, 

I try to use your moneybird V2 api but i'm a bit stuck. 

I get the following error: 
Fatal error: Uncaught exception 'Picqer\Financials\Moneybird\Exceptions\ApiException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in vendor\picqer\moneybird-php-client\src\Picqer\Financials\Moneybird\Connection.php on line 373

Can you please help me?

Thanks in advance.

**Comment by stephangroen** [comment]
This can happen if either the (intermediate) certificates are not correctly installed on the remote server, or your server doesn't recognize/accept the intermediate SSL certificates. 

The certificates on the Moneybird server seem correct. You could contact Moneybird about this, maybe they can verify the chain on their side is correct.

**Comment by CNVeerman** [comment]
Thanks, It was the certificate on my server. I added the file cacert.pem and set the location in php.ini 
This fixed the problem. 
Still I'm doing something wrong. 

First I made a file with the following code: 

```
require __DIR__ . '/vendor/autoload.php';
$connection = new \Picqer\Financials\Moneybird\Connection();
$connection->setRedirectUrl('http://localhost:8080/callback');
$connection->setClientId('CLIENTID');
$connection->setClientSecret('CLIENTSECRET');
$connection->redirectForAuthorization();
```

This gives an AutorizationCode. 

Then I added the autorizationcode to this part: 

```
require __DIR__ . '/vendor/autoload.php';

$connection = new \Picqer\Financials\Moneybird\Connection();
$connection->setRedirectUrl('http://localhost:8080/callback');
$connection->setClientId('CLIENTID');
$connection->setClientSecret('SECRET');

$connection->setAuthorizationCode('AUTHORIZATIONCODE');

$moneybird = new \Picqer\Financials\Moneybird\Moneybird($connection);

try {
    $connection->connect();
} catch (\Exception $e) {
    throw new Exception('Could not connect to Moneybird: ' . $e->getMessage());
}
```

But when I run the second part it gives me an error saying the authorazation code is expired or withdrawn. 

I hope you can help me establish the connection. 

Thanks in advance.

**Comment by stephangroen** [comment]
You're welcome!

You should try it with the example.php file and work from there. It has to be something wrong in the auth process on your side.

**Comment by CNVeerman** [comment]
Thanks! I have a connection.
