### ISSUE TITLE
Fatal error: curl_reset() 

### ISSUE THREAD

**Issue by CNVeerman** [picqer/moneybird-php-client#49]
Hello, 

I installed your API with composer on my local computer. After moving to a server I get the following Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset()

Do I need to upgrade the server to PHP 5.5 ? 
Or is this because I didn't install the API with composer again op the server? 
I can't use composer on the server so I hope there is an other solution if this is the problem. 

Thanks in advance,

**Comment by stephangroen** [comment]
Yes, this function is not available < PHP 5.5.

See: http://php.net/manual/en/function.curl-reset.php `(PHP 5 >= 5.5.0, PHP 7)`
