### ISSUE TITLE
Authorization code is not a requirement

### ISSUE THREAD

**Issue by EliasZ** [picqer/moneybird-php-client#5]
When using Moneybird, setting an access token is sufficient to perform authenticated requests (`Picqer\Financials\Moneybird\Connection->setAccessToken()`). However, in `Picqer\Financials\Moneybird\Connection->createRequest()` it is required to set the authorization code as it is checked upon with `Picqer\Financials\Moneybird\Connection->needsAuthentication()`.

**Comment by stephangroen** [comment]
You are right. I'll look into it :)
