### ISSUE TITLE
404 on example

### ISSUE THREAD

**Issue by robertragas** [picqer/moneybird-php-client#50]
Hello,

I have a question about the example code. I am trying to save a contact as in your example.
$contact = $moneybird->contact();
$contact->company_name = 'foo';
$contact->save();

But on this and other action I try I get a 404 error.
Picqer\Financials\Moneybird\Exceptions\ApiException : Error 404: {"error":"404 Not Found"}

I have checked the accesstoken etc. but they seem correct and work when I used the curl command. Any idea what i'm doing wrong?

**Comment by stephangroen** [comment]
Are any other calls working? For example are you able to retrieve invoices?

**Comment by robertragas** [comment]
Ahhh, nevermind. I see now that the administration id is needed to get the correct information. Thought it would be connected somehow when you give permission :) Closing the topic. 

Thanks for providing the php client :)

**Comment by stephangroen** [comment]
Good to know you got it sorted out! Thanks!
