### ISSUE TITLE
Set API status as error code

### ISSUE THREAD

**Issue by roelvanduijnhoven** [picqer/moneybird-php-client#55]
When a 429 error is spawned by MoneyBird the `Picqer\Financials\Moneybird\Exceptions\ApiException` exception is thrown. I would except the `$code` property to be 429. However it is empty! Therefore you need to parse the `$message` yourself.

Do you agree? If so I can implement it this way.

**Comment by stephangroen** [comment]
I agree! Sorry for the late response.

**Comment by stephangroen** [comment]
Seems already done in #54
