### ISSUE TITLE
Allow access to the Moneybird::$connection object

### ISSUE THREAD

**Issue by holtkamp** [picqer/moneybird-php-client#59]
We use [PHP-DI](http://php-di.org/) as dependency injection container which allows us to:
- configure a Connection object
- configure a Moneybird object using the acquired connection:

``` php
[
  Picqer\Financials\Moneybird\Connection::class => object()->constructor()
        ->method('setClientId', 'X')
        ->method('setClientSecret', 'Y')
        ->method('setRedirectUrl', 'Z'),
  Picqer\Financials\Moneybird\Moneybird::class => object()->constructor(get(Picqer\Financials\Moneybird\Connection::class)),
]
```

Then the Moneybird object can be injected like:

``` php
class Administration{

    /**
     * @Inject
     *
     * @var \Picqer\Financials\Moneybird\Moneybird
     */
    private $apiClient;

    public function execute(){
        var_dump($this->apiClient->administration->get());
    }
}
```

This works well. However, after determining the Administration, the Connection object needs to be updated with the `administrationId`. However, we can not access the connection of the Moneybird object.

Any suggestion on how to do this? Maybe the $connection property should be made public / or be accessible using a getter function?

**Comment by stephangroen** [comment]
I see no problem in creating a getter function for the connection.

**Comment by holtkamp** [comment]
see https://github.com/picqer/moneybird-php-client/pull/62
