### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mbardelmeijer** [picqer/moneybird-php-client#60]
Would be nice if there would be pagination support out of the box. Any ideas how to implement it? If i have the time i can PR it.

**Comment by stephangroen** [comment]
I think the best thing to do is read the Link header as stated in their docs to determine next page and create a recursive function to continue to load all the pages. Their should also be a way to control this, for example to have an optional page param so users do not always have to load all pages.

**Comment by vissr** [comment]
Same problem here, fix for me was quite easy.
Added to Connection.php:

`public $page = 1;
  public $per_page = 50;`

Then added this to the return url in the function formatUrl() in Connection.php:
`'.json?page='.$this->page.'&per_page='.$this->per_page;`

So now, on my front-end I can use it like this:

`$connection = connect($redirectUrl, $clientId, $clientSecret);
$connection->page = 3;
`

Edit: unfortunately this breaks filterable :(

**Comment by stephangroen** [comment]
I'll look into this when I find some time. A PR is always welcome, that doesn't break existing code :)

**Comment by PaulEmich** [comment]
I opened a PR for this #79

**Comment by stephangroen** [comment]
PR #79 merged
