### ISSUE TITLE
Creating an invoice

### ISSUE THREAD

**Issue by Paradoxis** [picqer/moneybird-php-client#61]
I'd like to create an invoice, but I need to send data to the endpoint. Currently I can't find any method to do so except for the `insert()` method (I'm assuming it makes a POST call to that endpoint). Is there a way this is possible or do I need to edit the code to add the functionality? Thanks

This is the code I have:

```php
use \Picqer\Financials\Moneybird;

$client = new Moneybird\Connection();
$client->setClientId(CONFIG_API_ID);
$client->setAccessToken(CONFIG_API_TOKEN);

$invoice = new Moneybird\Moneybird($client);
$invoice->salesInvoice()->insert()
```

**Comment by stephangroen** [comment]
``` php
// Example: Create a new contact
$contact = $moneybird->contact();

$contact->company_name = 'Picqer';
$contact->firstname = 'Stephan';
$contact->lastname = 'Groen';
$contact->save();
var_dump($contact); // Contact object (as saved in Moneybird)
```

The same concept applies for a SalesInvoice.

**Comment by Paradoxis** [comment]
Hi, thanks for the answer but this seems to generate the incorrect url, when the endpoint is generated the url `https://moneybird.com/api/v2/contacts.json` is selected which gives me a 404 error. 

Moneybird expects an administration_id to be passed in the URL: `https://moneybird.com/api/v2/{administration_id}/contacts.json`, is there a way to set this? I can't seem to get the code to work.

**Comment by Ugoku** [comment]
```
$connection = new MoneybirdAPI\Connection();
$connection->setAdministrationId(42);
```

where 42 is your administration ID

**Comment by roydekleijn** [comment]
is there a detailed example of creating an invoice?

**Comment by stephangroen** [comment]
No, but if you read the entity it shouldnt be too hard.
