### ISSUE TITLE
Use @property annotations to improve usability in IDEs

### ISSUE THREAD

**Issue by holtkamp** [picqer/moneybird-php-client#63]
Currently it sometimes is 'difficult' to use the Entities as used by the API since it is not directly clear what properties are available / involved. 

This can be improved by, for example:

```php

/**
 * @property string $state The state of this SalesInvoice, either 'x', 'y', or 'z'
 * @property <type> <name> <description> XYZ
 */
class SalesInvoice {
 //content
}

```

Now IDE's will detect the ```state``` property, making it easier to use the Entities. More info here: https://phpdoc.org/docs/latest/references/phpdoc/tags/property.html

**Comment by stephangroen** [comment]
You're welcome to submit a PR with the phpdoc :)

**Comment by holtkamp** [comment]
@stephangroen ok, will do, maybe keep this issue open until then? 😄

**Comment by stephangroen** [comment]
Closing this issue. PR's are welcome and I will refer to this issue when people ask for it.
