### ISSUE TITLE
Improve datatypes of unserialized model

### ISSUE THREAD

**Issue by holtkamp** [picqer/moneybird-php-client#64]
When working on https://github.com/picqer/moneybird-php-client/issues/63 I noticed (again) that: 

- identifiers that are marked as type ```integer``` [in the API documentation](http://developer.moneybird.com/api/sales_invoices/#post_sales_invoices), are of type ```string``` in the model, for example:
  - sales_invoice[id]
  - sales_invoice[contact_id]
- dates that can be parsed into ```DateTime``` or ```DateTimeImmutable``` objects, are of type ```string``` in the model, for example:
  - sales_invoice[invoice_date]
  - sales_invoice[paid_at]

I think the integers are incorrectly returned as a string by the API, I will contact Moneybird about that. 

About the dates, should we consider detecting 'date' strings and assemble a ```DateTimeImmutable``` for that?

**Comment by stephangroen** [comment]
Identifiers are given as strings on purpose by Moneybird. This is stated in their changelog:

> Many JSON parsing tools out of the box don’t work well with our long integer IDs. Therefore we’ve updated the API to always return these IDs as strings instead.

Automatically creating `DateTimeImmutable` objects would require a new major version as this breaks backwards compatibility. I do like it, but we might consider some other changes if we're going to get to a new version.

**Comment by holtkamp** [comment]
>Identifiers are given as strings on purpose by Moneybird.

aah, well, ok 😄 missed that one. What is your stance on using ```integer``` for them in this library? I would say PHP can deal with it properly...

>would require a new major version as this breaks backwards compatibility. ... we might consider some other changes...
Indeed, so maybe collect these things in a separate branch. I think I will collect some of these things in my fork, then you can cherry-pick the stuff you like / agree with.

**Comment by holtkamp** [comment]
@stephangroen I though a bit on how improved support for datatypes could be realized. Unfortunately I do not see an 'easy' way: automatic detection. For example: users might use string that appear an integer or DateTime as descriptions. So we need to keep track of _what_ field has/should have _what_ kind of datatype. With other words: metadata. 

Did you ever consider using a library for the serialization (PHP => JSON) and deserialization (JSON => PHP) process? For example: http://jmsyst.com/libs/serializer

**Comment by stephangroen** [comment]
As long as we do not automatically form any string to a specific datatype, I don't see the usecase for adding complexity or the need to include extra libraries. I'd like to try and keep the library as clean as possible so it's easy to understand for all developers.

**Comment by stephangroen** [comment]
For dates their could be a setting/switch on the library to either get DateTimeImmutable objects or strings, depending on the preference. For example https://github.com/box/spout#datetime-formatting handles it this way.
