### ISSUE TITLE
Implement filtering on recurring sales invoices

### ISSUE THREAD

**Issue by Ugoku** [picqer/moneybird-php-client#65]
As of [October 13](http://developer.moneybird.com/changelog/), recurring sales invoices can be filtered. It would be great if this was supported, i.e. `$invoices = $connection->recurringSalesInvoice()->filter(['contact_id' => 1234567890]);`

Is this as simple as adding `use Filterable` to the `RecurringSalesInvoice` class? If so I'd be happy to provide a PR.

**Comment by stephangroen** [comment]
This should work with Filterable indeed (if the docs are correct). You can test it and submit a PR if you want. I'd be happy to merge.
