### ISSUE TITLE
credit invoice

### ISSUE THREAD

**Issue by Spreeuw** [picqer/moneybird-php-client#67]
Misschien kijk ik er overheen, maar ik kan niet vinden hoe ik een credit invoice aanmaak van een factuur ([duplicate_creditinvoice](http://developer.moneybird.com/api/sales_invoices/#patch_sales_invoices_id_duplicate_creditinvoice))
Zit dit hier nog niet in?

**Comment by stephangroen** [comment]
Not implemented yet, but feel free to submit a PR :)

**Comment by Spreeuw** [comment]
fixed by #69
