### ISSUE TITLE
$moneybird->administration()->get() returns 404 when administrationId is set

### ISSUE THREAD

**Issue by Spreeuw** [picqer/moneybird-php-client#73]
Since this is a global function, in my opinion this should also work when administrationId is set. I'm not sure about the best approach around this with $connection->formatUrl() here, since this always sets the id when it's available. I'm open to suggestions!

**Comment by hiranthi** [comment]
And here I thought I was missing something, because after setting the administrationId listing the administrations didn't work anymore. Good to know I was not.

**Comment by joshuadegier** [comment]
Looks like the API doesn't support looking up an administration based on ID such as other Entities do: https://developer.moneybird.com/api/administration/. 

I don't see any ways to make this work unless there is an extra call in `Picqer\Financials\Moneybird\MoneyBird` that saves the list of administrations on each request. But that would add a single request each time you use the API while fetching that data is not needed in every request. I think you're best off by caching the `$moneybird->administration()->getAll()` response with the administration id as key and make your own implementation to fetch the details afterwards.

**Comment by donquixote** [comment]
The solution is to give Administration a different Connection object than other models:
- Administration needs a connection without administration id.
- Other models need a connection with administration id.

Here is what I currently have locally:
```php
class Administration extends Model {

    [..]

    /**
     * @param \Picqer\Financials\Moneybird\Connection $connection
     * @param array $attributes
     */
    public function __construct(Connection $connection, array $attributes = [])
    {
        parent::__construct($connection->withoutAdministrationId(), $attributes);
    }
}
```
What I changed:
- Add a few "wither" methods to Connection, which clone the connection and set properties of the clone, hence making it behave like an immutable object. This makes it easy for Administration to use its own version of Administration.
- Override the constructor for Administration, to use a different Connection object.

**Comment by donquixote** [comment]
> Looks like the API doesn't support looking up an administration based on ID such as other Entities do: > https://developer.moneybird.com/api/administration/.

`$moneybird->administration()->get()` works for me to fetch all administrations, after the change explained above.
