### ISSUE TITLE
Mark as sent equivalent

### ISSUE THREAD

**Issue by sDeVette** [picqer/moneybird-php-client#81]
As I'm switching over from the v1 of the API with the youngguns wrapper, I'm looking for a markAsSent equivalent. Right now the Invoices get marked as a concept because I'm sending the PDF's with a custom email, together with other attachments. I've tried to set the sent_at property but it doesn't have the required effect.
Any help would be greatly appreciated!

**Comment by hiranthi** [comment]
You can use $invoice->sendInvoice('Manual');

The 'Manual' stands for that you're sending the invoice manually ([delivery methods](https://developer.moneybird.com/api/sales_invoices/#patch_sales_invoices_id_send_invoice)). Other options are Post (Moneybird will send the document through post, although this one seems to be vanishing, the option can't be used when adding invoices manually anymore) and Email (the default).

**Comment by casperbakker** [comment]
Thanks @hiranthi for helping out!
