### ISSUE TITLE
Filter Contacts if they exist

### ISSUE THREAD

**Issue by dna75** [picqer/moneybird-php-client#98]
I'm trying to filter on company_names if they exist or not. I see it working with for example a sales invoice status (draft) but is it also possible to filter contacts? With code:

$contact = $moneybird->contact()->filter([
  'company_name' => 'Tester'
]);
var_dump($contact);

**Comment by Beee4life** [comment]
I'm interested to know as well... Or any other way to check if a client exists already, preferably with email as unique identifier.

**Comment by stephangroen** [comment]
https://developer.moneybird.com/api/contacts/#get_contacts_example1
